services:
  accounts:
    image: "alishoumar/account-service:1.0.0"
    container_name: "account-service"
    ports:
      - "8080:8080"
    deploy:
      resources:
        limits:
          memory: 700m
    networks:
      - banking
  loans:
    image: "alishoumar/loan-service:1.0.0"
    container_name: "loan-service"
    ports:
      - "8090:8090"
    deploy:
      resources:
        limits:
          memory: 700m
    networks:
      - banking
  cards:
    image: "alishoumar/card-service:1.0.0"
    container_name: "card-service"
    ports:
      - "9000:9000"
    deploy:
      resources:
        limits:
          memory: 700m
    networks:
      - banking
networks:
  banking:
    driver: "bridge"