services:

  rabbitmq:
    image: "rabbitmq"
    container_name: rabbitmq
    hostname: "rabbitmq"
    ports:
      - "5672:5672"
    healthcheck:
      test: "rabbitmq-diagnostics check_port_connectivity"
      interval: 10s
      timeout: 5s
      retries: 19
      start_period: 10s
    extends:
      file: common-config.yml
      service: network-deploy-service

  redis:
    image: "redis"
    container_name: "redis"
    ports:
      - "6379:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 19
      start_period: 10s
    extends:
      file: common-config.yml
      service: network-deploy-service

  account-db:
    container_name: "account-db"
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: "accountsdb"
    extends:
      file: common-config.yml
      service: microservice-db-config

  loan-db:
    container_name: "loan-db"
    ports:
      - "3307:3306"
    environment:
      MYSQL_DATABASE: "loansdb"
    extends:
      file: common-config.yml
      service: microservice-db-config

  card-db:
    container_name: "card-db"
    ports:
      - "3308:3306"
    environment:
      MYSQL_DATABASE: "cardsdb"
    extends:
      file: common-config.yml
      service: microservice-db-config

  config-server:
    image: "alishoumar/config-server:1.0.0"
    container_name: "config-server"
    ports:
      - "8071:8071"
    depends_on:
      rabbitmq:
        condition: service_healthy
    healthcheck:
      test: ["CMD-SHELL", "wget -q -O - http://localhost:8071/actuator/health/readiness | grep -q '\"status\":\"UP\"' || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 10s

    extends:
      file: common-config.yml
      service: microservice-base-config

  eureka-server:
    image: "alishoumar/eureka-server:1.0.0"
    hostname: "eureka-server"
    container_name: "eureka-server"
    ports:
      - "8070:8070"
    depends_on:
      config-server:
        condition: service_healthy
    healthcheck:
      test: ["CMD-SHELL", "wget -q -O - http://localhost:8070/actuator/health/readiness | grep -q '\"status\":\"UP\"' || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 10s
    environment:
      SPRING_APPLICATION_NAME: "eureka-server"
    extends:
      file: common-config.yml
      service: microservices-eureka-config


  account-service:
    image: "alishoumar/account-service:1.0.0"
    container_name: "account-service"
    ports:
      - "8080:8080"
    depends_on:
      account-db:
        condition: service_healthy
      eureka-server:
        condition: service_healthy
    healthcheck:
      test: [ "CMD-SHELL", "wget -q -O - http://localhost:8080/actuator/health/readiness | grep -q '\"status\":\"UP\"' || exit 1" ]
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 10s
    environment:
      SPRING_APPLICATION_NAME: "account-service"
      SPRING_DATASOURCE_URL: "jdbc:mysql://account-db:3306/accountsdb"
    extends:
      file: common-config.yml
      service: microservice-configserver-config

  loan-service:
    image: "alishoumar/loan-service:1.0.0"
    container_name: "loan-service"
    ports:
      - "8090:8090"
    depends_on:
      loan-db:
        condition: service_healthy
      eureka-server:
        condition: service_healthy
    healthcheck:
      test: [ "CMD-SHELL", "wget -q -O - http://localhost:8090/actuator/health/readiness | grep -q '\"status\":\"UP\"' || exit 1" ]
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 10s
    environment:
      SPRING_APPLICATION_NAME: "loan-service"
      SPRING_DATASOURCE_URL: "jdbc:mysql://loan-db:3306/loansdb"
    extends:
      file: common-config.yml
      service: microservice-configserver-config

  card-service:
    image: "alishoumar/card-service:1.0.0"
    container_name: "card-service"
    ports:
      - "9000:9000"
    depends_on:
      card-db:
        condition: service_healthy
      eureka-server:
        condition: service_healthy
    healthcheck:
      test: [ "CMD-SHELL", "wget -q -O - http://localhost:9000/actuator/health/readiness | grep -q '\"status\":\"UP\"' || exit 1" ]
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 10s
    environment:
      SPRING_APPLICATION_NAME: "card-service"
      SPRING_DATASOURCE_URL: "jdbc:mysql://card-db:3306/cardsdb"
    extends:
      file: common-config.yml
      service: microservice-configserver-config

  gateway-server:
    image: "alishoumar/gateway-server:1.0.0"
    container_name: "gateway-server"
    ports:
      - "8072:8072"
    depends_on:
      account-service:
        condition: service_healthy
      card-service:
        condition: service_healthy
      loan-service:
        condition: service_healthy
      redis:
        condition: service_healthy
    environment:
      SPRING_APPLICATION_NAME: "gateway-server"
      SPRING_DATA_REDIS_HOST: "redis"
      SPRING_REDIS_PORT: 6379
    extends:
      file: common-config.yml
      service: microservices-eureka-config

networks:
  banking:
    driver: "bridge"