server:
  port: 9000

spring:
  application:
    name: "card-service"
  profiles:
    active: "default"

  datasource:
    url: jdbc:mysql://localhost:3308/cardsdb
    username: "root"
    password: "root"
  jpa:
    show-sql: true
  sql:
    init:
      mode: always

#  config:
#    import: "configserver:http://localhost:8071"

  rabbitmq:
    host: "localhost"
    port: 5672
    username: "guest"
    password: "guest"

management:
  endpoints:
    web:
      exposure:
        include: "*"